# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2017 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- project:
    name: virt
    jobs:
      - virt-amd64-0-prep
      - virt-amd64-1-migrate-t
      - virt-amd64-1-migrate-x
      - virt-amd64-1-migrate-a
      - virt-amd64-1-migrate-b
      - virt-amd64-2-cross-rel
      - virt-amd64-3-misc
      - virt-amd64-4-qemuqa-x
      - virt-amd64-5-libvirtqa-x
      - virt-amd64-4-qemuqa-b
      - virt-amd64-5-libvirtqa-b
      - virt-amd64-6-cleanup
      - virt-s390x-1-migrate-x
      - virt-s390x-0-prep
      - virt-s390x-1-migrate-a
      - virt-s390x-1-migrate-b
      - virt-s390x-2-cross-rel
      - virt-s390x-3-misc
      - virt-s390x-0-prep
      - virt-s390x-6-cleanup
      - virt-ppc64-1-migrate-x
      - virt-ppc64-1-migrate-a
      - virt-ppc64-1-migrate-b
      - virt-ppc64-2-cross-rel
      - virt-ppc64-3-misc
      - virt-ppc64-6-cleanup

- defaults:
    name: global
    description: |
        Virt Ubuntu Server QA Jenkins Job

        *** STOP ***
        Do NOT edit this job through the web
        This job is managed by Jenkins Job Builder and stored on Github via the URL below:
        https://github.com/canonical-server/jenkins-jobs
        *** STOP ***
    properties:
      - build-discarder:
          num-to-keep: 25
