# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2017 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- project:
    name: virt
    jobs:
      - virt-prep-amd64
      - virt-migrate-amd64-t
      - virt-migrate-amd64-x
      - virt-migrate-amd64-a
      - virt-migrate-amd64-b
      - virt-cross-release-amd64
      - virt-qemu-qa-amd64
      - virt-libvirt-qa-amd64
      - virt-migrate-s390x-x
      - virt-prep-s390x
      - virt-migrate-s390x-a
      - virt-migrate-s390x-b
      - virt-cross-release-s390x
      - virt-prep-ppc64el
      - virt-migrate-ppc64el-x
      - virt-migrate-ppc64el-a
      - virt-migrate-ppc64el-b
      - virt-cross-release-ppc64el
      - virt-cleanup-amd64
      - virt-cleanup-ppc64el
      - virt-cleanup-s390x

- defaults:
    name: global
    description: |
        Virt Ubuntu Server QA Jenkins Job

        *** STOP ***
        Do NOT edit this job through the web
        This job is managed by Jenkins Job Builder and stored on Github via the URL below:
        https://github.com/canonical-server/jenkins-jobs
        *** STOP ***
    properties:
      - build-discarder:
          num-to-keep: 25
