# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2017 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- job:
    name: cloud-init-copr-build
    node: torkoal
    triggers:
      - timed: "H 23 * * *"
    publishers:
      - email-server-crew
      - trigger:
          project: cloud-init-copr-test-7
          threshold: SUCCESS
    builders:
      - shell: |
          #!/bin/bash
          set -e
          rm -rf *

          git clone --depth 1 https://github.com/CanonicalLtd/server-test-scripts
          git clone --single-branch https://git.launchpad.net/cloud-init
          pushd cloud-init

          export PYVER=python2
          export http_proxy="http://squid.internal:3128"
          export https_proxy="$http_proxy"

          retry_cmd="./tools/run-centos 7 --srpm --artifact"
          for i in {1..3}; do [ $i -gt 1 ] && sleep 5m; $retry_cmd && s=0 && break || s=$?; done; (exit $s)

          popd
          SRPM=$(realpath cloud-init/*.src.rpm)
          cd server-test-scripts/cloud-init

          retry_cmd="./copr_build.py --dev --srpm $SRPM"
          for i in {1..3}; do [ $i -gt 1 ] && sleep 20m; $retry_cmd && s=0 && break || s=$?; done; (exit $s)

- job:
    name: cloud-init-copr-test-7
    node: torkoal
    builders:
      - shell: |
          #!/bin/bash
          set -e
          rm -rf *

          export http_proxy="http://squid.internal:3128"
          export https_proxy="$http_proxy"

          git clone --depth 1 https://github.com/CanonicalLtd/server-test-scripts
          cd server-test-scripts/cloud-init
          ./copr_test -vv 7
