# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2016 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- job:
    name: cloud-init-integration-nocloud-kvm-x
    node: torkoal
    triggers:
      - timed: "H 12 * * *"
    publishers:
      - email-server-crew
      - archive-results
      - trigger:
          project: cloud-init-integration-nocloud-kvm-b
          threshold: FAILURE
    builders:
      - integration-nocloud-kvm:
          release: xenial

- job:
    name: cloud-init-integration-nocloud-kvm-b
    node: torkoal
    publishers:
      - email-server-crew
      - archive-results
      - trigger:
          project: cloud-init-integration-nocloud-kvm-c
          threshold: FAILURE
    builders:
      - integration-nocloud-kvm:
          release: bionic

- job:
    name: cloud-init-integration-nocloud-kvm-c
    node: torkoal
    publishers:
      - email-server-crew
      - archive-results
    builders:
      - integration-nocloud-kvm:
          release: cosmic

- job:
    name: cloud-init-integration-nocloud-kvm-d
    node: torkoal
    publishers:
      - email-server-crew
      - archive-results
    builders:
      - integration-nocloud-kvm:
          release: disco

- builder:
    name: integration-nocloud-kvm
    builders:
      - shell: |
          release="{release}"
          if [ -z "$TMPDIR" -a "$(hostname)" = "torkoal" ]; then
              export TMPDIR=/var/lib/jenkins/tmp/
          fi
          sudo rm -Rf *
          git clone https://github.com/CanonicalLtd/server-test-scripts.git
          ./server-test-scripts/cloud-init/daily_deb.sh -v $release
          deb=$(echo "$PWD/cloud-init_"*.deb)
          if [ ! -f "$deb" ]; then
              echo "Failed to get deb? [$deb]";
              exit 1;
          fi
          # extract hash from cloud-init...-g[a-f][a-f]..._all.deb
          hash=$(echo "$deb" | sed 's,.*-g\([0-9a-f]\+\)-.*,\1,')
          echo "deb=$(basename $deb) hash=$hash"
          git clone https://git.launchpad.net/cloud-init
          cd cloud-init
          git checkout --quiet "$hash"
          git log --max-count=1 --pretty=oneline HEAD
          no_proxy=launchpad.net https_proxy="http://squid.internal:3128" tox \
            -e citest -- run "--os-name=$release" \
            --platform=nocloud-kvm --preserve-data --data-dir=results \
            --verbose "--deb=$deb"
