# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2016 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- job:
    name: cloud-init-integration-ec2-x
    node: metal-amd64
    triggers:
      - timed: "H 0 * * 0"
    publishers:
      - email-server-crew
      - archive-results
      - trigger:
          project: cloud-init-integration-ec2-terminate
          threshold: FAILURE
    builders:
      - integration-ec2:
          release: xenial

- job:
    name: cloud-init-integration-ec2-a
    node: metal-amd64
    triggers:
      - timed: "H 0 * * 1"
    publishers:
      - email-server-crew
      - archive-results
      - trigger:
          project: cloud-init-integration-ec2-terminate
          threshold: FAILURE
    builders:
      - integration-ec2:
          release: artful

- job:
    name: cloud-init-integration-ec2-b
    node: metal-amd64
    triggers:
      - timed: "H 0 * * 2"
    publishers:
      - email-server-crew
      - archive-results
      - trigger:
          project: cloud-init-integration-ec2-terminate
          threshold: FAILURE
    builders:
      - integration-ec2:
          release: bionic

- job:
    name: cloud-init-integration-ec2-c
    node: metal-amd64
    triggers:
      - timed: "H 0 * * 3"
    publishers:
      - email-server-crew
      - archive-results
      - trigger:
          project: cloud-init-integration-ec2-terminate
          threshold: FAILURE
    builders:
      - integration-ec2:
          release: cosmic

- builder:
    name: integration-ec2
    builders:
      - shell: |
          release="{release}"
          export http_proxy=http://squid.internal:3128
          export apt_proxy=http://squid.internal:3128

          sudo rm -Rf *
          git clone https://github.com/CanonicalLtd/server-test-scripts.git
          git clone https://git.launchpad.net/cloud-init
          cd cloud-init
          ../server-test-scripts/cloud-init/daily_deb.sh -v $release
          tox -e citest -- run --os-name $release \
            --platform ec2 --preserve-data --data-dir results \
            --verbose --deb cloud-init_*_all.deb

- job:
    name: cloud-init-integration-ec2-terminate
    node: metal-amd64
    publishers:
      - email-server-crew
    builders:
      - shell: |
          export http_proxy=http://squid.internal:3128
          export apt_proxy=http://squid.internal:3128

          sudo rm -Rf *
          git clone https://github.com/CanonicalLtd/server-test-scripts
          ./server-test-scripts/cloud-init/ec2_cleanup.py
