# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2016 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- job-template:
    name: cloud-init-integration-proposed-x-trigger
    node: metal-amd64
    triggers:
      - timed: "H 10 * * *"
    builders:
      - trigger-proposed-integration:
          release: xenial
          triggerwhat: cloud-init-integration-proposed-x

- job-template:
    name: cloud-init-integration-proposed-x
    node: metal-amd64
    auth-token: BUILD_ME
    publishers:
        - email-server-crew
        - archive-results
    builders:
      - proposed-integration:
          release: xenial

- job-template:
    name: cloud-init-integration-proposed-z-trigger
    node: metal-amd64
    publishers: []
    triggers:
      - timed: "H 10 * * *"
    builders:
      - trigger-proposed-integration:
          release: zesty
          triggerwhat: cloud-init-integration-proposed-z

- job-template:
    name: cloud-init-integration-proposed-z
    node: metal-amd64
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: zesty
    publishers:
        - email-server-crew
        - archive-results

- job-template:
    name: cloud-init-integration-proposed-a-trigger
    node: metal-amd64
    publishers: []
    triggers:
      - timed: "H 10 * * *"
    builders:
      - trigger-proposed-integration:
          release: artful
          triggerwhat: cloud-init-integration-proposed-a

- job-template:
    name: cloud-init-integration-proposed-a
    node: metal-amd64
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: artful
    publishers:
        - email-server-crew
        - archive-results

- builder:
    name: proposed-integration
    builders:
      - shell: |
          release="{release}"
          export http_proxy=http://squid.internal:3128
          export apt_proxy=http://squid.internal:3128

          set -e
          sudo rm -Rf cloud-init
          mkdir cloud-init
          cd cloud-init
          pull-lp-source cloud-init $release-proposed
          d=$(for d in *; do [ -d "$d" ] && echo "$d" && exit 0; done)
          cd "$d"
          echo "Running with source for $d"
          mirror="http://archive.ubuntu.com/ubuntu/"
          python3 -m tests.cloud_tests run \
              --os-name="$release" \
              --repo="deb $mirror $release-proposed main" \
              --preserve-data --data-dir="../results" \
              --verbose

- builder:
    name: trigger-proposed-integration
    builders:
      - shell: |
          set -e
          release={release}
          triggerwhat={triggerwhat}
          sudo rm -f version_lookup.py
          wget https://raw.githubusercontent.com/canonical-server/test-scripts/master/launchpad/version_lookup.py
          chmod +x version_lookup.py
          proposed=$(./version_lookup.py -r $release -p Proposed -s Published cloud-init)

          if [ "$proposed" != "" ]; then
            curl -X POST --netrc-file $JENKINS_HOME/jenkins-bot-creds http://server-team-jenkins-be.internal:8080/server/job/$triggerwhat/build?token=BUILD_ME
          fi


